package sibarum.dasum.gui.msdf;

import org.apache.maven.plugin.MojoExecutionException;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Emits a Java {@code Icons} class with one {@code public static final
 * int} per selected glyph. Includes a {@code byName(String)} lookup that
 * accepts both original library names ({@code "arrow-up"}) and the
 * normalized constant names ({@code "ARROW_UP"}).
 *
 * <p>Collision policy: if two source names normalize to the same Java
 * constant, the build fails with a list of all colliding source names.
 * No silent overwrite — the user must drop one or supply an alias map
 * (the latter is future work).
 */
final class IconsCodegen {

    private IconsCodegen() {}

    static File generate(IconConfig cfg, Map<String, Integer> selected, String libraryName)
            throws MojoExecutionException {
        if (cfg.generatedSourcesDir == null) {
            throw new MojoExecutionException("icons.generatedSourcesDir is required.");
        }
        if (cfg.packageName == null || cfg.packageName.isBlank()) {
            throw new MojoExecutionException("icons.packageName is required.");
        }
        String className = (cfg.className == null || cfg.className.isBlank()) ? "Icons" : cfg.className;

        // Normalize all names, detecting collisions early so the error
        // message lists every colliding source name rather than failing
        // at javac with a "duplicate field" diagnostic.
        Map<String, List<String>> normalizedToSources = new LinkedHashMap<>();
        for (String source : selected.keySet()) {
            String norm = IconNameNormalizer.normalize(source);
            normalizedToSources.computeIfAbsent(norm, k -> new ArrayList<>()).add(source);
        }
        List<String> collisions = new ArrayList<>();
        for (Map.Entry<String, List<String>> e : normalizedToSources.entrySet()) {
            if (e.getValue().size() > 1) {
                collisions.add(e.getKey() + " <- " + e.getValue());
            }
        }
        if (!collisions.isEmpty()) {
            throw new MojoExecutionException(
                "Icon name collisions (multiple source names normalize to the same constant):\n  "
                + String.join("\n  ", collisions));
        }

        File pkgDir = new File(cfg.generatedSourcesDir, cfg.packageName.replace('.', '/'));
        if (!pkgDir.exists() && !pkgDir.mkdirs()) {
            throw new MojoExecutionException("Failed to create generated-sources dir: " + pkgDir);
        }
        File javaFile = new File(pkgDir, className + ".java");

        StringBuilder sb = new StringBuilder(64 * 1024);
        sb.append("// Generated by dasum-msdf-maven-plugin. DO NOT EDIT.\n");
        sb.append("// Icon library: ").append(libraryName == null ? "(unknown)" : libraryName).append('\n');
        sb.append("// Source manifest: ").append(cfg.manifest == null ? "(inline)" : cfg.manifest.getName()).append('\n');
        sb.append("package ").append(cfg.packageName).append(";\n\n");
        sb.append("import java.util.HashMap;\n");
        sb.append("import java.util.Map;\n\n");
        sb.append("/**\n");
        sb.append(" * Generated icon codepoint constants. One field per glyph baked into\n");
        sb.append(" * the matching MSDF atlas. Use with the dasum-core icon helper:\n");
        sb.append(" * <pre>\n");
        sb.append(" *   Component icon = Icon.of(").append(className).append(".SEARCH, Em.of(1.2f), labelColor);\n");
        sb.append(" * </pre>\n");
        sb.append(" *\n");
        sb.append(" * <p>{@link #byName(String)} accepts either the original library name\n");
        sb.append(" * (e.g. {@code \"arrow-up\"}) or the normalized constant name\n");
        sb.append(" * (e.g. {@code \"ARROW_UP\"}).\n");
        sb.append(" */\n");
        sb.append("public final class ").append(className).append(" {\n\n");
        sb.append("    private ").append(className).append("() {}\n\n");

        // Constants, in source manifest order. Each carries a javadoc
        // line preserving the original library name so search-by-name in
        // the IDE finds it even if you're looking for the kebab-case form.
        for (Map.Entry<String, Integer> e : selected.entrySet()) {
            String source = e.getKey();
            int cp = e.getValue();
            String constant = IconNameNormalizer.normalize(source);
            sb.append("    /** Source name: {@code \"").append(source).append("\"} */\n");
            sb.append("    public static final int ").append(constant)
              .append(" = 0x").append(Integer.toHexString(cp).toUpperCase()).append(";\n");
        }
        sb.append('\n');

        // byName lookup table — populated lazily on first call to keep
        // <clinit> light for apps that never use the table.
        sb.append("    private static Map<String, Integer> byNameMap;\n\n");
        sb.append("    /**\n");
        sb.append("     * Look up an icon's codepoint by name. Accepts either the\n");
        sb.append("     * original source-library name or the normalized constant name.\n");
        sb.append("     * Returns {@code -1} for unknown names.\n");
        sb.append("     */\n");
        sb.append("    public static int byName(String name) {\n");
        sb.append("        Map<String, Integer> m = byNameMap;\n");
        sb.append("        if (m == null) {\n");
        sb.append("            m = new HashMap<>(").append(selected.size() * 4).append(");\n");
        for (Map.Entry<String, Integer> e : selected.entrySet()) {
            String source = e.getKey();
            int cp = e.getValue();
            String constant = IconNameNormalizer.normalize(source);
            sb.append("            m.put(\"").append(source).append("\", 0x")
              .append(Integer.toHexString(cp).toUpperCase()).append(");\n");
            // Only add the constant alias when it actually differs from
            // the source (most icon libraries use kebab-case so the two
            // differ; for already-uppercase names we skip the duplicate).
            if (!constant.equals(source)) {
                sb.append("            m.put(\"").append(constant).append("\", 0x")
                  .append(Integer.toHexString(cp).toUpperCase()).append(");\n");
            }
        }
        sb.append("            byNameMap = m;\n");
        sb.append("        }\n");
        sb.append("        Integer v = m.get(name);\n");
        sb.append("        return v == null ? -1 : v;\n");
        sb.append("    }\n");
        sb.append("}\n");

        try {
            Files.writeString(javaFile.toPath(), sb.toString(), StandardCharsets.UTF_8);
        } catch (IOException e) {
            throw new MojoExecutionException("Failed writing generated Icons class to " + javaFile, e);
        }
        return javaFile;
    }
}
