Args = --initialize-at-run-time=sibarum.dasum.gui.natives.glfw.Glfw \
       --initialize-at-run-time=sibarum.dasum.gui.natives.glfw.GlfwCallbacks \
       --initialize-at-run-time=sibarum.dasum.gui.natives.gl.Gl \
       --initialize-at-run-time=sibarum.dasum.gui.natives.NativeLibLoader
